const HttpStatus = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

const UserRole = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  TECHNICIAN: 'TECHNICIAN',
  VIEWER: 'VIEWER',
});

const AssetStatus = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  RETIRED: 'RETIRED',
  DISPOSED: 'DISPOSED',
});

const AssetCategory = Object.freeze({
  HARDWARE: 'HARDWARE',
  SOFTWARE: 'SOFTWARE',
  VEHICLE: 'VEHICLE',
  FURNITURE: 'FURNITURE',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER',
});

const MaintenanceStatus = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

module.exports = {
  HttpStatus,
  UserRole,
  AssetStatus,
  AssetCategory,
  MaintenanceStatus,
};
